name: pupil_env

channels:
- defaults

dependencies:
- python==3.7
- numpy==1.18.1
- opencv
- pyyaml==5.3
- scikit-image==0.16.2
- scipy==1.4.1
- tqdm==4.43.0
- imutils==0.5.3
- conda-forge::dlib==19.19.0
- pip:
  - filterpy
